#!/usr/bin/env python3
"""
Clean up artifacts generated by this demo. Useful between full runs when you
want a fresh slate without manually `rm`-ing dozens of files.

Two scopes:

  --local    Delete generated files in data/ and outputs/ (synthetic CSVs,
             chunked JSONLs, manifests, predictions, downloaded outputs).
             Reference inputs (wlan0_ipv4_flows_db.csv, topology.json, the
             two ghost_iot_*_yesterday.jsonl files) are PROTECTED and never
             touched.

  --remote   Attempt to delete files from the Archetype AI platform that this
             demo has uploaded, using the file_uids in
             data/uploaded_file_ids.jsonl. The platform's DELETE endpoint isn't
             documented in this repo's README — the script tries DELETE
             /v0.5/files/{file_uid} and falls back to /v0.5/files/{filename}.
             Failures are reported but don't abort the remaining deletes.

Default: --dry-run, no flags. Prints what *would* be deleted; touches nothing.

Examples:
    python cleanup.py                        # dry-run, show local + remote candidates
    python cleanup.py --local                # delete local artifacts
    python cleanup.py --local --keep-csv     # delete everything except generated CSVs
    python cleanup.py --remote               # attempt platform-side deletes
    python cleanup.py --local --remote       # both
"""

from __future__ import annotations

import argparse
import glob
import json
import os
import shutil
import sys

import requests

REPO_DIR = os.path.dirname(os.path.abspath(__file__))


# ---------------------------------------------------------------------------
# What's safe to delete
# ---------------------------------------------------------------------------
PROTECTED_FILES = {
    "data/wlan0_ipv4_flows_db.csv",          # original GHOST-IoT seed CSV
    "data/topology.json",                     # 3-home topology, hand-authored
    "data/ghost_iot_home_yesterday.jsonl",   # small reference input (sections 2-6)
    "data/ghost_iot_devices_yesterday.jsonl", # small reference input
}

# Patterns of files generated during a run.
LOCAL_FILE_PATTERNS = [
    # Synthetic CSVs
    "data/wifi_flows_multihome_*.csv",
    "data/wlan0_ipv4_flows_*gb.csv",
    "data/wlan0_ipv4_flows_*mb.csv",
    "data/wlan0_ipv4_flows_large.csv",
    # Chunk + reduce manifests
    "data/manifest_chunked.jsonl",
    "data/manifest_per_device_hour.jsonl",
    "data/manifest_bucket_reduce_*.jsonl",
    "data/manifest_device_day.jsonl",
    "data/manifest_user_day.jsonl",
    "data/manifest_house_day.jsonl",
    # Predictions
    "data/predictions_*.jsonl",
    # Reduce-stage JSONLs
    "data/bucket_reduce_*.jsonl",
    "data/device_day_reduce.jsonl",
    "data/user_day_reduce.jsonl",
    "data/house_day_reduce.jsonl",
    # Section 7 (legacy hourly/daily) — kept in case stale files exist
    "data/ghost_iot_home_*gb*.jsonl",
    "data/ghost_iot_home_*mb*.jsonl",
    "data/ghost_iot_devices_*gb*.jsonl",
    "data/ghost_iot_devices_*mb*.jsonl",
    "data/ghost_iot_home_hourly*.jsonl",
    "data/ghost_iot_home_daily_*.jsonl",
    # Upload manifests
    "data/uploaded_file_ids.txt",
    "data/uploaded_file_ids.jsonl",
    "data/uploaded_file_ids_*.txt",
    "data/uploaded_file_ids_*.jsonl",
]

LOCAL_DIRECTORY_PATTERNS = [
    "data/per_device_hour",
    "data/per_device_hour_*",
]

# outputs/ subdirectories are always candidates (they're per-job).
OUTPUTS_ROOT = "outputs"

CSV_PATTERNS = {"data/wifi_flows_multihome_*.csv", "data/wlan0_ipv4_flows_*gb.csv",
                "data/wlan0_ipv4_flows_*mb.csv", "data/wlan0_ipv4_flows_large.csv"}


def fmt_bytes(n: int) -> str:
    if n >= 1024 ** 3:
        return f"{n / 1024**3:.2f} GB"
    if n >= 1024 ** 2:
        return f"{n / 1024**2:.1f} MB"
    if n >= 1024:
        return f"{n / 1024:.0f} KB"
    return f"{n} B"


def gather_local(keep_csv: bool) -> tuple[list[str], list[str]]:
    """Returns (files, directories) under REPO_DIR that match cleanup patterns."""
    files: list[str] = []
    directories: list[str] = []

    for pat in LOCAL_FILE_PATTERNS:
        if keep_csv and pat in CSV_PATTERNS:
            continue
        for p in glob.glob(os.path.join(REPO_DIR, pat)):
            rel = os.path.relpath(p, REPO_DIR)
            if rel in PROTECTED_FILES:
                continue
            if os.path.isfile(p):
                files.append(p)

    for pat in LOCAL_DIRECTORY_PATTERNS:
        for p in glob.glob(os.path.join(REPO_DIR, pat)):
            if os.path.isdir(p):
                directories.append(p)

    outputs_path = os.path.join(REPO_DIR, OUTPUTS_ROOT)
    if os.path.isdir(outputs_path):
        for entry in sorted(os.listdir(outputs_path)):
            sub = os.path.join(outputs_path, entry)
            if os.path.isdir(sub):
                directories.append(sub)

    return sorted(set(files)), sorted(set(directories))


def directory_total_bytes(path: str) -> int:
    total = 0
    for root, _dirs, fnames in os.walk(path):
        for fn in fnames:
            try:
                total += os.path.getsize(os.path.join(root, fn))
            except OSError:
                pass
    return total


def delete_local(files: list[str], directories: list[str], dry_run: bool) -> None:
    print()
    print("=" * 60)
    print(" Local cleanup")
    print("=" * 60)
    if not files and not directories:
        print("  Nothing to delete.")
        return

    total_bytes = 0
    if files:
        print(f"  {len(files)} file(s):")
        for p in files:
            try:
                size = os.path.getsize(p)
            except OSError:
                size = 0
            total_bytes += size
            rel = os.path.relpath(p, REPO_DIR)
            print(f"    {fmt_bytes(size):>10}  {rel}")

    if directories:
        print(f"  {len(directories)} director(ies):")
        for p in directories:
            size = directory_total_bytes(p)
            total_bytes += size
            rel = os.path.relpath(p, REPO_DIR)
            n_files = sum(len(fs) for _r, _ds, fs in os.walk(p))
            print(f"    {fmt_bytes(size):>10}  {rel}/  ({n_files:,} files)")

    print(f"  Total: {fmt_bytes(total_bytes)}")
    if dry_run:
        print("  (dry-run — pass --local to actually delete)")
        return

    deleted = 0
    for p in files:
        try:
            os.unlink(p)
            deleted += 1
        except OSError as e:
            print(f"  WARN  could not delete {p}: {e}")
    for p in directories:
        try:
            shutil.rmtree(p)
            deleted += 1
        except OSError as e:
            print(f"  WARN  could not delete {p}: {e}")
    print(f"  Deleted {deleted}/{len(files) + len(directories)} entries.")


# ---------------------------------------------------------------------------
# Platform-side cleanup
# ---------------------------------------------------------------------------
def load_env() -> tuple[str, str]:
    env_path = os.path.join(REPO_DIR, ".env")
    if os.path.exists(env_path):
        with open(env_path) as f:
            for line in f:
                line = line.strip()
                if "=" in line and not line.startswith("#"):
                    k, v = line.split("=", 1)
                    os.environ.setdefault(k, v)
    return os.environ.get("ATAI_API_KEY", ""), os.environ.get("ATAI_API_ENDPOINT", "")


def gather_remote() -> list[dict]:
    """Read uploaded_file_ids.jsonl entries (filename, file_uid)."""
    path = os.path.join(REPO_DIR, "data", "uploaded_file_ids.jsonl")
    if not os.path.exists(path):
        return []
    out: list[dict] = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                out.append(json.loads(line))
            except json.JSONDecodeError:
                continue
    return out


def try_delete(api_key: str, base_url: str, filename: str, file_uid: str) -> tuple[bool, str]:
    """Attempt the most likely DELETE endpoints for a single file. Returns (ok, message)."""
    headers = {"Authorization": f"Bearer {api_key}"}
    candidates = []
    if file_uid:
        candidates.append(("file_uid", f"{base_url}/files/{file_uid}"))
    if filename:
        candidates.append(("filename", f"{base_url}/files/{filename}"))

    if not candidates:
        return False, "no file_uid or filename"

    last_status = ""
    for label, url in candidates:
        try:
            resp = requests.delete(url, headers=headers, timeout=20)
        except requests.RequestException as e:
            last_status = f"{label}: {type(e).__name__}: {e}"
            continue
        if resp.ok:
            return True, f"{label} OK ({resp.status_code})"
        last_status = f"{label}: HTTP {resp.status_code} {resp.text[:120]}"
        # 404 is the closest signal that this endpoint doesn't exist.
        # Try the next candidate.

    return False, last_status


def delete_remote(entries: list[dict], dry_run: bool, base_url: str, api_key: str) -> None:
    print()
    print("=" * 60)
    print(" Remote cleanup")
    print("=" * 60)
    print(f"  {len(entries)} file(s) recorded in data/uploaded_file_ids.jsonl")
    if dry_run:
        print("  (dry-run — pass --remote to attempt platform-side deletes)")
        if entries:
            print()
            print("  Sample of files we'd attempt to delete:")
            for e in entries[:5]:
                print(f"    file_uid={e.get('file_uid', '')[:20]:<20}  filename={e.get('filename', '')}")
            if len(entries) > 5:
                print(f"    ... and {len(entries) - 5} more")
        return

    if not entries:
        print("  No files to delete.")
        return

    if not api_key or not base_url:
        print("  ERROR: ATAI_API_KEY / ATAI_API_ENDPOINT not set; skipping remote cleanup.")
        return

    ok = 0
    fail = 0
    print()
    print("  Note: the DELETE endpoint isn't documented in this repo's README.")
    print("  Trying /v0.5/files/{file_uid} first, then /v0.5/files/{filename}.")
    print()

    failures: list[tuple[str, str]] = []
    for i, e in enumerate(entries, start=1):
        filename = e.get("filename", "")
        file_uid = e.get("file_uid", "")
        success, msg = try_delete(api_key, base_url, filename, file_uid)
        if success:
            ok += 1
            if i <= 5 or i == len(entries):
                print(f"  [{i:>4}/{len(entries)}] OK     {filename:<60}  {msg}")
        else:
            fail += 1
            failures.append((filename, msg))
            if i <= 5:
                print(f"  [{i:>4}/{len(entries)}] FAIL   {filename:<60}  {msg}")

    print()
    print(f"  Result: {ok} deleted, {fail} failed.")
    if fail and failures:
        print(f"  First few failures:")
        for fn, msg in failures[:5]:
            print(f"    - {fn}: {msg}")
        if ok == 0:
            print()
            print("  None of the DELETE endpoints worked. The platform may not expose a")
            print("  per-file delete API — confirm with the platform team. As a workaround,")
            print("  rename your local files (e.g. add a session suffix) before re-uploading.")


def main():
    parser = argparse.ArgumentParser(description="Clean up demo artifacts (local and/or platform-side).")
    parser.add_argument("--local", action="store_true",
                        help="Delete local generated artifacts (CSVs, JSONLs, manifests, outputs/).")
    parser.add_argument("--remote", action="store_true",
                        help="Attempt to delete platform-side files via the Files API.")
    parser.add_argument("--keep-csv", action="store_true",
                        help="With --local: preserve generated synthetic CSVs (re-running prep is fast otherwise).")
    args = parser.parse_args()

    dry_run = not (args.local or args.remote)

    if dry_run:
        print("Dry-run mode — nothing will be deleted. Pass --local and/or --remote to act.")
        print("(Use --keep-csv with --local to preserve generated synthetic CSVs.)")

    files, directories = gather_local(args.keep_csv)
    if args.local or dry_run:
        delete_local(files, directories, dry_run=dry_run or not args.local)

    if args.remote or dry_run:
        api_key, api_endpoint = load_env()
        base_url = f"{api_endpoint}/v0.5" if api_endpoint else ""
        entries = gather_remote()
        delete_remote(entries, dry_run=dry_run or not args.remote, base_url=base_url, api_key=api_key)

    if dry_run:
        print()
        print("To actually delete:")
        print("  python cleanup.py --local              # local only")
        print("  python cleanup.py --remote             # platform only")
        print("  python cleanup.py --local --remote     # both")


if __name__ == "__main__":
    main()
